# Generated by Django 4.1.3 on 2022-12-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=200)),
                ("price", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=250)),
            ],
        ),
    ]
