# Generated by Django 4.1.3 on 2022-12-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Services", new_name="Service",),
    ]
