# Generated by Django 4.1.3 on 2022-12-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_rename_services_service"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service", old_name="service", new_name="product",
        ),
    ]
