# Generated by Django 4.1.3 on 2022-12-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_rename_service_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
