# Generated by Django 4.1.3 on 2022-12-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_rename_date_appoinment_date1_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="doctor", old_name="name", new_name="Name",),
    ]
